# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
  node: circleci/node@4.7

workflows:
  sample:
    jobs:
      - node/test:
          version: '14.19'
          pkg-manager: npm
      - node/test:
          version: '16.10'
          pkg-manager: npm
      - node/test:
          version: '17.4'
          pkg-manager: npm
